const fs = require('fs');
const path = require('path');

const contentFilePath = path.join(__dirname, '..', 'data', 'content.json');

// Helper to get relative timestamp so they sort in correct order (Quiet Hours first)
const baseTime = Date.now();

const defaultVideos = [
  // DOCUMENTARY
  {
    id: "mock-doc-quiet-hours",
    type: "video",
    title: "Quiet Hours",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Independent Commission",
    duration: "18:42",
    description: "A day-in-the-life documentary following three Lagosians across a single Sunday — intimate, unhurried, and deeply honest.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 1000
  },
  {
    id: "mock-doc-tide-trade",
    type: "video",
    title: "Tide & Trade",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2022",
    client: "Lagos Waterfront Project",
    duration: "24:10",
    description: "Following traders and fishermen along the Lagos waterfront.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 2000
  },
  {
    id: "mock-doc-the-makers",
    type: "video",
    title: "The Makers",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Arts Foundation Nigeria",
    duration: "31:05",
    description: "Profiles of five craftspeople keeping traditional Nigerian crafts alive.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 3000
  },
  {
    id: "mock-doc-city-sound",
    type: "video",
    title: "City of Sound",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Rolling Stone Africa",
    duration: "15:30",
    description: "Inside Lagos nightlife and the afrobeats scene.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 4000
  },
  {
    id: "mock-doc-harvest",
    type: "video",
    title: "Harvest",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2022",
    client: "Ogun Agricultural Initiative",
    duration: "22:15",
    description: "A farming community in Ogun State through the seasons.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 5000
  },
  {
    id: "mock-doc-beyond-frame",
    type: "video",
    title: "Beyond the Frame",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "documentary",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Fashion Week Committee",
    duration: "12:40",
    description: "Behind-the-scenes of a Lagos fashion week.",
    tags: ["documentary"],
    featured: false,
    createdAt: baseTime - 6000
  },

  // MUSIC VIDEOS
  {
    id: "mock-mv-neon-reverie",
    type: "video",
    title: "Neon Reverie",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Lady V",
    duration: "3:45",
    description: "Neon-drenched overnight shoot in Lagos — slow-motion and light painting.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 7000
  },
  {
    id: "mock-mv-ojo-ibi",
    type: "video",
    title: "Ọjọ Ìbí",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Tayo & Friends",
    duration: "4:12",
    description: "Birthday celebration narrative music video.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 8000
  },
  {
    id: "mock-mv-midnight-lagos",
    type: "video",
    title: "Midnight Lagos",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "DJ Xclusive",
    duration: "5:20",
    description: "Narrative short following a musician through one night in Lagos.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 9000
  },
  {
    id: "mock-mv-gold-rush",
    type: "video",
    title: "Gold Rush",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Burna Star",
    duration: "3:10",
    description: "Afrobeats energy — fast cuts, Lagos streets at golden hour.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 10000
  },
  {
    id: "mock-mv-still-waters",
    type: "video",
    title: "Still Waters",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Sena",
    duration: "4:30",
    description: "Slow, melancholic piece shot on a Lagos creek.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 11000
  },
  {
    id: "mock-mv-move",
    type: "video",
    title: "Move",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "music-video",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "P-Square Crew",
    duration: "3:05",
    description: "Dance-forward afrobeats video with colorful sets.",
    tags: ["music-video"],
    featured: false,
    createdAt: baseTime - 12000
  },

  // WEDDING
  {
    id: "mock-wed-adaeze-chidi",
    type: "video",
    title: "Adaeze & Chidi",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "wedding",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Adaeze & Chidi",
    duration: "15:00",
    description: "A traditional Igbo wedding ceremony — from sunrise preparations to midnight reception.",
    tags: ["wedding"],
    featured: false,
    createdAt: baseTime - 13000
  },
  {
    id: "mock-wed-folake-seun",
    type: "video",
    title: "Folake & Seun",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "wedding",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Folake & Seun",
    duration: "18:30",
    description: "A Yoruba traditional and white wedding — two ceremonies, one love story.",
    tags: ["wedding"],
    featured: false,
    createdAt: baseTime - 14000
  },
  {
    id: "mock-wed-amaka-daniel",
    type: "video",
    title: "Amaka & Daniel",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "wedding",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Amaka & Daniel",
    duration: "12:15",
    description: "Destination wedding at a Lagos beachfront estate.",
    tags: ["wedding"],
    featured: false,
    createdAt: baseTime - 15000
  },
  {
    id: "mock-wed-kemi-tobi",
    type: "video",
    title: "Kemi & Tobi",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "wedding",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Kemi & Tobi",
    duration: "10:45",
    description: "Intimate court ceremony and garden reception — 40 guests, pure emotion.",
    tags: ["wedding"],
    featured: false,
    createdAt: baseTime - 16000
  },
  {
    id: "mock-wed-blessing-emeka",
    type: "video",
    title: "Blessing & Emeka",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "wedding",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Blessing & Emeka",
    duration: "22:40",
    description: "Grand reception at Eko Hotel — 500 guests, full cinematic production.",
    tags: ["wedding"],
    featured: false,
    createdAt: baseTime - 17000
  },

  // BRAND ADVERT
  {
    id: "mock-ad-brand-pulse",
    type: "video",
    title: "Brand Pulse — Hero Film",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "advert",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Brand Pulse",
    duration: "1:00",
    description: "60-second hero ad for Lagos lifestyle brand.",
    tags: ["advert"],
    featured: false,
    createdAt: baseTime - 18000
  },
  {
    id: "mock-ad-glow-campaign",
    type: "video",
    title: "Glow Campaign",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "advert",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Glow Skincare",
    duration: "0:30",
    description: "30-second skincare campaign — clean, minimal, Lagos summer.",
    tags: ["advert"],
    featured: false,
    createdAt: baseTime - 19000
  },
  {
    id: "mock-ad-moves-sneaker",
    type: "video",
    title: "Moves — Sneaker Ad",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "advert",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Moves Footwear",
    duration: "0:45",
    description: "Fast-cut sneaker ad shot on Lagos streets.",
    tags: ["advert"],
    featured: false,
    createdAt: baseTime - 20000
  },

  // CHURCH HIGHLIGHTS
  {
    id: "mock-ch-sunday-echoes",
    type: "video",
    title: "Sunday Echoes",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "church",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Echoes of Hope",
    duration: "8:15",
    description: "Full Sunday service highlight — worship, message, altar call.",
    tags: ["church"],
    featured: false,
    createdAt: baseTime - 21000
  },
  {
    id: "mock-ch-encounter-conf",
    type: "video",
    title: "Encounter Conference",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "church",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2023",
    client: "Encounter Ministries",
    duration: "12:30",
    description: "3-day conference highlight — 4,000 attendees, 3 cameras, 1 story.",
    tags: ["church"],
    featured: false,
    createdAt: baseTime - 22000
  },
  {
    id: "mock-ch-easter-sunday",
    type: "video",
    title: "Easter Sunday",
    src: "",
    sourceUrl: "",
    thumb: "",
    width: 0,
    height: 0,
    embedUrl: "",
    videoProvider: "direct",
    fileCode: "",
    useHls: false,
    category: "church",
    seriesKey: "",
    seriesName: "",
    seriesDescription: "",
    seriesYear: "",
    year: "2024",
    client: "Easter Team",
    duration: "6:45",
    description: "Easter Sunday cinematic highlight — sunrise service to main congregation.",
    tags: ["church"],
    featured: false,
    createdAt: baseTime - 23000
  }
];

if (!fs.existsSync(contentFilePath)) {
  console.error('Error: content.json does not exist. Run the server once to initialize it.');
  process.exit(1);
}

try {
  const fileData = fs.readFileSync(contentFilePath, 'utf8');
  const store = JSON.parse(fileData);
  
  if (!store.items) store.items = [];
  
  let addedCount = 0;
  for (const defaultVid of defaultVideos) {
    // Check if a video with the same ID or same title already exists
    const exists = store.items.some(item => item.id === defaultVid.id || (item.type === 'video' && item.title === defaultVid.title));
    if (!exists) {
      store.items.push(defaultVid);
      addedCount++;
    }
  }
  
  if (addedCount > 0) {
    fs.writeFileSync(contentFilePath, JSON.stringify(store, null, 2), 'utf8');
    console.log(`Successfully seeded ${addedCount} default videos to database content.json.`);
  } else {
    console.log('All default videos are already present in content.json. No changes made.');
  }
} catch (err) {
  console.error('Error reading/writing content.json:', err);
  process.exit(1);
}
